### ISSUE TITLE
The last `--jobserver-auth` flag should be used

### ISSUE THREAD

**Issue by ojeda** [rust-lang/jobserver-rs#66]
The first `--jobserver-auth` it finds is used, instead of the last like the Make manual asks:

> Be aware that the `MAKEFLAGS` variable may contain multiple instances of the `--jobserver-auth=` option. Only the last instance is relevant.

```console
$ echo 'fn main() {}' | MAKEFLAGS='--jobserver-auth= --jobserver-auth=3,4' rustc -
warning: failed to connect to jobserver from environment variable `MAKEFLAGS="--jobserver-auth= --jobserver-auth=3,4"`: cannot parse jobserver environment variable value: expected `fifo:PATH` or `R,W`, found ``
  |
  = note: the build environment is likely misconfigured
```

From https://github.com/rust-lang/rust/issues/120515.

**Comment by weihanglo** [comment]
[Link to that paragraph](https://www.gnu.org/software/make/manual/make.html#Job-Slots)

This is definitely a bug in the implementation and jobserver should try its best following how GNU make works.

The question is whether this is a breaking change needing a major version bump. Personally I don't think so. Having it in a major version bump will introduce much more inconsistency.

**Comment by NobodyXu** [comment]
Does jobserver need to do the same for `--jobserver-fds` and uses the last instance of it?

If both `--jobserver-fds` and `--jobserver-auth` is present, which one shall we use?

Shall we just try both?

**Comment by weihanglo** [comment]
Good question!

According to [this announcement](https://lists.gnu.org/archive/html/info-gnu/2016-05/msg00013.html), `--jobserver-fds` was something internally used by make itself before made public.

There is no reason both of them are present. And to me, it seems better for `--jobserver-auth` to take precedence over the other.

**Comment by NobodyXu** [comment]
Thanks!
