### ISSUE TITLE
Would it be a new tag push to crates.io?

### ISSUE THREAD

**Issue by getong** [rust-lang/jobserver-rs#69]
https://github.com/getong/rust-esplora-client/actions/runs/7746969254/job/21126393201?pr=1

I run a ci error on it, the tag is 0.1.27, but the code base has been fixed.
I don't know why this error occurs, I think it could be solved by making a new tag.

**Comment by weihanglo** [comment]
Yeah. The maintainers of jobserver need to publish a new version with those fixes, and I believe we're waiting for other pull requests merged.

---

@petrochenkov, I assumed 0.1.27 was released along with this commit <https://github.com/rust-lang/jobserver-rs/commit/a503383a3395f62e229e1660111c934f2bc03d8e>. However, it doesn't seem to be the case, as `.cargo_vcs_info.json` shows it is released under e44749b4ae602fb91746c429d80b0c7d159dd2e6 which is not even included in this repo history 😆.
