### ISSUE TITLE
Add git tags for crates.io releases

### ISSUE THREAD

**Issue by FreezyLemon** [rust-lang/jobserver-rs#94]
Hello, the latest git tag in the repo is for 0.1.26. It would be nice to have tags that correspond to the crates.io releases to make it easier to compare the changes in each version. Thanks!

**Comment by weihanglo** [comment]
While it's nice to tag each release, there is no guarantee that git tags on GitHub and released tarballs on crates.ui have the same source. To me I usually use http://diff.rs to compare diff between versions.

**Comment by FreezyLemon** [comment]
> there is no guarantee that git tags on GitHub and released tarballs on crates.ui have the same source.

Good point, although I'm not really arguing from a point of trust here. For me specifically, it's more about convenience (using the github web UI to diff the release tags). That said, thanks for the recommendation! That site looks really useful

**Comment by weihanglo** [comment]
Did my best recovering git tags. Those commit shas don't really match what were recorded in `.cargo_vcs_info.json` on crates.io, but sources should be identical I believe.

**Comment by weihanglo** [comment]
Going to close this as resolved. Let me know if you have any further question :)
