### ISSUE TITLE
Run tests on musl in CI

### ISSUE THREAD

**Issue by NobodyXu** [rust-lang/jobserver-rs#95]
I think we should also run CI on musl, on linux musl and gnu have enough differences for them to be considered as two different targets.

_Originally posted by @NobodyXu in https://github.com/rust-lang/jobserver-rs/issues/87#issuecomment-2094694302_

**Comment by weihanglo** [comment]
https://github.com/rust-lang/jobserver-rs/blob/c0c2898efbdc616c00f86ecfa68831e74488bba3/.github%2Fworkflows%2Fmain.yml#L46

We have some basic tests on MUSL. What do you consider adding?

**Comment by NobodyXu** [comment]
Oh it's already added when the musl regression is found.

Sorry that I forgot it 😂
